# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cwclock < Formula
  desc ""
  homepage "https://gitlab.cwcloud.tech/oss/cwclock"
  version "1.13.8"

  on_macos do
    url "https://gitlab.cwcloud.tech/oss/cwclock/-/releases/v1.13.8/downloads/cwclock_1.13.8_darwin_all.tar.gz"
    sha256 "750bf58d196eccea8763cf38831b6613b267c8ca173fb3c24417df30e6f1fce4"

    define_method(:install) do
      bin.install "cwclock"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://gitlab.cwcloud.tech/oss/cwclock/-/releases/v1.13.8/downloads/cwclock_1.13.8_linux_amd64.tar.gz"
      sha256 "d7e79d794af561712f753e2f9facede8c927c09d27af932134401821be62a7f9"
      define_method(:install) do
        bin.install "cwclock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gitlab.cwcloud.tech/oss/cwclock/-/releases/v1.13.8/downloads/cwclock_1.13.8_linux_arm64.tar.gz"
      sha256 "4311366ef77e4ead279d9abb3ccc33bcb851b93b29d26ea5e5538b9c82d45c7b"
      define_method(:install) do
        bin.install "cwclock"
      end
    end
  end
end
