# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cwclock < Formula
  desc ""
  homepage "https://gitlab.cwcloud.tech/oss/cwclock"
  version "1.13.3"

  on_macos do
    url "https://gitlab.cwcloud.tech/oss/cwclock/-/releases/v1.13.3/downloads/cwclock_1.13.3_darwin_all.tar.gz"
    sha256 "50f810a24b1dc63b619a69c50afebc8307d6677fdfd795c5266ac99def16561e"

    define_method(:install) do
      bin.install "cwclock"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://gitlab.cwcloud.tech/oss/cwclock/-/releases/v1.13.3/downloads/cwclock_1.13.3_linux_amd64.tar.gz"
      sha256 "66ed78c12c9c9afce7312f457a37326b3521ef17d3f66d4281a9553e556cd17d"
      define_method(:install) do
        bin.install "cwclock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gitlab.cwcloud.tech/oss/cwclock/-/releases/v1.13.3/downloads/cwclock_1.13.3_linux_arm64.tar.gz"
      sha256 "443889e76c0ff4e8839799c0aaede02b5d36a4c6e9c57ad1abfc12eb2ba07cc9"
      define_method(:install) do
        bin.install "cwclock"
      end
    end
  end
end
