services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    env_file:
      - .env.example
    ports:
      - "8080:8080"

  ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: ui
    env_file:
      - .env.example
