services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.validate
      target: tests
    volumes:
      - .:/app
    working_dir: /app
    command: go test -v ./...
  linter:
    build:
      context: .
      dockerfile: Dockerfile.validate
      target: linter
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
