---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cwclock-chart.fullname" . }}-jwt-secret
  labels:
  {{- include "cwclock-chart.labels" . | nindent 4 }}
data:
  JWT_SECRET: {{ $.Values.api.jwt | b64enc }}
